export const GET_ALL_STUDENTS = 'GET_ALL_CONTACTS';
export const CREATE_NEW_STUDENT = 'CREATE_NEW_CONTACT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const FILTER_STUDENT_LIST = 'FILTER_STUDENT_LIST';
export const ADD_STUDENT_LIST = 'ADD_STUDENT_LIST';